### PR TITLE
Replace broken footer scraping with static footer

### PR DESCRIPTION
**Pull request by toupeira**
The previous code started to fail because of a layout change on www.doku-zug.ch. I copied the static footer from the error pages now.

### CODE REVIEW

**Review by huerlisi — APPROVED** [review]
Looks good to me, thanks!

**Comment by huerlisi** [comment]
There is a failing test on Travis, but it was failing in the previous MR already.

**Comment by toupeira** [comment]
@huerlisi should be fixed now with https://github.com/CyTeam/katalog/pull/6

**Comment by toupeira** [comment]
Cleaning up old PRs... :joy:

**Pull request closed without merging**
