### PR TITLE
Fix sphinxql syntax errors

### PR DESCRIPTION
**Pull request by toupeira**
Fixes these errors:

```
ThinkingSphinx::SyntaxError: sphinxql: syntax error, unexpected '*', expecting FROM or ',' near '* (1.5 - is_local) AS custom_weight FROM `dossier_core`, `dossier_delta` WHERE MATCH('@* (\"\\&\" | (\"\\&\" | \"\\&*\"))') AND `is_topic` = 0 AND `sphinx_deleted` = 0 ORDER BY `custom_weight` DESC LIMIT 0, 20 OPTION field_weights=(title=500, parent_title=5, keywords=10), max_matches=1000000; SHOW META' - SELECT *, weight() * (1.5 - is_local) AS custom_weight FROM `dossier_core`, `dossier_delta` WHERE MATCH('@* (\"\\&\" | (\"\\&\" | \"\\&*\"))') AND `is_topic` = 0 AND `sphinx_deleted` = 0 ORDER BY `custom_weight` DESC LIMIT 0, 20 OPTION field_weights=(title=500, parent_title=5, keywords=10), max_matches=1000000; SHOW META
```

```
ThinkingSphinx::SyntaxError: index dossier_core,dossier_delta: syntax error, unexpected ')' near '+))' - SELECT *, (weight() * (1.5 - is_local)) AS custom_weight FROM `dossier_core`, `dossier_delta` WHERE MATCH('@* (\"+\" | (+))') AND `is_topic` = 0 AND `sphinx_deleted` = 0 ORDER BY `custom_weight` DESC LIMIT 0, 20 OPTION field_weights=(title=500, parent_title=5, keywords=10), max_matches=1000000; SHOW META
```

I'm *assuming* these changes are backwards-compatible with older Sphinx versions :)

### CODE REVIEW

**Comment by huerlisi** [comment]
Looks good to me!

**Review by huerlisi — APPROVED** [review]
LGTM

**Comment by toupeira** [comment]
@huerlisi hmm the spec was passing locally with sphinxsearch 2.2.11, but Travis has another issue:

```
  1) Dossier.by_text should work with & and +
     Failure/Error: expect { Dossier.by_text('&').count }.to_not raise_exception
       expected no Exception, got #<ThinkingSphinx::SyntaxError: sphinxql: syntax error, unexpected WEIGHT, expecting IDENT (or 11 other tokens) near 'weight() * (1.5 - is_local)) AS custom_weight FROM `dossier_core`, `dossier_delta` WHERE MATCH('@* (\"\\&\" | (\"\"\\&\" | \"\\&*\"\"))') AND `is_topic` = 0 AND `sphinx_deleted` = 0 ORDER BY `custom_weight` DESC LIMIT 0, 20 OPTION field_weights=(title=500, parent_title=5, keywords=10), max_matches=1000000; SHOW META' - SELECT *, (weight() * (1.5 - is_local)) AS custom_weight FROM `dossier_core`, `dossier_delta` WHERE MATCH('@* (\"\\&\" | (\"\"\\&\" | \"\\&*\"\"))') AND `is_topic` = 0 AND `sphinx_deleted` = 0 ORDER BY `custom_weight` DESC LIMIT 0, 20 OPTION field_weights=(title=500, parent_title=5, keywords=10), max_matches=1000000; SHOW META> with backtrace:
         # ./spec/models/dossier_sphinx_spec.rb:73:in `block (5 levels) in <top (required)>'
         # ./spec/models/dossier_sphinx_spec.rb:73:in `block (4 levels) in <top (required)>'
         # ./spec/models/dossier_sphinx_spec.rb:72:in `block (3 levels) in <top (required)>'
     # ./spec/models/dossier_sphinx_spec.rb:73:in `block (4 levels) in <top (required)>'
     # ./spec/models/dossier_sphinx_spec.rb:72:in `block (3 levels) in <top (required)>'
```

**Comment by toupeira** [comment]
Cleaning up old PRs... :joy:

**Pull request closed without merging**
